### ISSUE TITLE
U-Term: Make clear the role of F1 (exit BBS) and F3 (ASCII/PETSCII) key functions

### ISSUE THREAD

**Issue by sblendorio** [xlar54/ultimateii-dos-lib#19]
It seems that people turn on and off the C64 and re-load U-Term from disk every time they want to change BBS:
https://www.facebook.com/1943034422597090/videos/602093900263708

...but they can just presss F1! We have to find a way to communicate it clearly. For example, some instructions on main screen are now obsolete, and we can use that part of screen more efficiently (e.g. "ensure that Command Line interface is enabled", just because now there is a UCI detection when program starts, then it gives user instructions on how to turn it on)

**Comment by xlar54** [comment]
If we can detect loss of connection, this would be a lot easier.  Maybe there is way, and i just hadnt discovered it.  Maybe attempting to read from the socket, when it is closed is reporting an error and we arent seeing it,

**Comment by xlar54** [comment]
Good question.  Ill reach out and ask him.

**Comment by sblendorio** [comment]
d8d102cf8d8984684282f85fc31589e618ea8fc7: Added a HELP screen, trying managing save and restore of the screen before and after displaying of instructions. Made a branch https://github.com/xlar54/ultimateii-dos-lib/tree/add_help_screen

Please, could you test this on your C128 in 80 column mode? On my one, during restoring phase, random characters are put on the screen. Gonna try with another C128 to know whether this bug is caused by a broken VDC on my C128 or not.

I think it could be a problem on my C128: I made a preliminary study that works perfectly on VICE (x128) emulator, you can download source and executable here:
https://www.dropbox.com/s/tqjq1y1xhdw9x3c/scr-save-restore.zip?dl=0
Build it with
    cl65 -t c128 scr.c scr-use.c -o scr-use128.prg

It works on x128 emulator, but has the problem I told before on the real thing.

**Comment by sblendorio** [comment]
This issue is getting stranger and stranger. Look at this source:
https://www.dropbox.com/s/9qrikv1btuf15ld/scr80.c?dl=0

in particular these lines should print the SAME address:
`	printf("vdc_saved_screen=%u\n",vdc_saved_screen);
	printf("ptr_vdc_screen=%u\n",ptr_vdc_screen);
`

...just because of this:

`unsigned char *ptr_vdc_screen = vdc_saved_screen;
`

but they are different. What do you think about it?

**Comment by sblendorio** [comment]
Tried studying this problem, but did not find a reason yet.

**Comment by sblendorio** [comment]
To give a more clear idea of what I see, here are two photos: the first is the "homepage" of Retroacademy BBS. 
![good_img_20190201_225555891](https://user-images.githubusercontent.com/2118813/52152060-67710500-2675-11e9-8b3d-4881a07e1a93.jpg)

Then, I pressed F1 to get the help screen, then pressed any key to get rid of it and come back to BBS screen. Here you can see at least 5 position in the screen where situation changed, with random characters:
![wasted_img_20190201_225546130](https://user-images.githubusercontent.com/2118813/52152105-840d3d00-2675-11e9-9b9d-5b23dc1d2682.jpg)

In the ASM code there are those two "patterns" for reading and writing from/to VDC memory:

    notyet_read:
        asm("bit $d600");
        asm("bpl %g", notyet_read);
        asm("lda $d601"); 

    ...

    notyet_write: 
        asm("bit $d600");
        asm("bpl %g", notyet_write);
        asm("sta $d601");

Could this way of writing and reading from/to VDC registry be wrong? Too fast or too sluggish?

(All this does NOT happen in C64 mode, where all goes on perfectly)

**Comment by xlar54** [comment]
Sure, will take a look on my 128d.  I just moved some things around, so might take me a day but will get back to you.

**Comment by sblendorio** [comment]
Also, I noticed in the code this snippet that writes and reads from $D601 and $D600 but **without** wait:

    void vdc_prepare(void) {
        asm("lda #$12");
        asm("sta $d600");
        asm("lda %v", vdc_hi);
        asm("sta $d601");
        asm("lda #$13");
        asm("sta $d600");
        asm("lda %v", vdc_lo);
        asm("sta $d601");
        asm("lda #$1f");
        asm("sta $d600");
    }

**Comment by sblendorio** [comment]
Just made a pull-request. In the current HELP screen there are the correct infos. I was wondering if the instructions contained in main screen are still meaningful ("Disable any emulated cartridges" is a check done by DETECT_UCI function and "Network links is in LInkUp state" is quite obvious). What about it?

If it all goes ok, let's merge this branch!

**Comment by xlar54** [comment]
I love it.  Automated checking is the way to go, good choice!  Yep, ship it whenever youre ready.  Was wondering your thoughts about integrating the irc client *into* the terminal?  Maybe down the road.  But it could make the codebase too big to fit into memory, especially on the 128 (cc65 provides actually less RAM to the 128 than the 64... go figure).  Anyway, great job on the fix.  With my recent move, I need to pick up an ethernet cable for the machines to get back online so Ill be off the radar for a day or so.

**Comment by sblendorio** [comment]
Good, I'm gonna merge it. For now I leave a basic HELP message 'cos we currently we have a few of commands (F3 and F7).

Regarding merging IRC Client and Terminal I share your doubt about the amount of memory: I'm writing code having in mind to keep final executable as small as possible. I just may write a "start menu" to choose the program to load like the actual "TERM-LOADER" but with an actual user interface.
