### ISSUE TITLE
Reported "afterlife.dynu.org" stopped working with 1.5 version

### ISSUE THREAD

**Issue by sblendorio** [xlar54/ultimateii-dos-lib#20]
User "Joonas Viskari" reports that AfterlifeBBS (afterlife.dynu.org : 6400) worked with 1.22 version but it does not work with 1.5+ :
https://www.facebook.com/groups/commodoresixtyfour/permalink/10155726173572172/?comment_id=10155729156632172

I tried to connect to Afterlife also with a PETSCII-compatible terminal for PC (SyncTerm), but for me it is almost offline.

Can you make some try and verify it?

**Comment by xlar54** [comment]
Was able to connect just now with cgterm (https://paradroid.automac.se/cgterm/).  will try with our current version also.  Seems odd if its just a single bbs.

**Comment by xlar54** [comment]
I think its wrong in the phonebook.  should be .com instead of .org

**Comment by xlar54** [comment]
yeah i was just on via .com on the lastest version.  works fine.

**Comment by sblendorio** [comment]
I will make a commit. But let's wait for another release... what do you think?

**Comment by sblendorio** [comment]
ok, I'm gonna do new release

**Comment by sblendorio** [comment]
Just made new release "v1.61". I tried but could not DELETE the old release "1.61" on github. Can you try to do it?

I also updated the release here: https://csdb.dk/release/index.php?id=174462

Can you give a try and, if it's all OK, close this issue?

**Comment by xlar54** [comment]
yep standby

**Comment by xlar54** [comment]
All good, thanks!
