### ISSUE TITLE
Detect of remote disconnection

### ISSUE THREAD

**Issue by sblendorio** [xlar54/ultimateii-dos-lib#27]
Maybe I found the way and it's incredibly simple. After reading data with uii_tcpsocketread, the length of the data read is:

    len_buff = uii_data[0] | (uii_data[1]<<8)

if len_buff is >0, then data is present. Otherwise there are **TWO** other options:
* len_buff == **-1** it means "no data is read, and **connection is still alive**"
* len_buff == **0** it means "**loss** of connection".

I tested it and implemented in the following lines in UltimateTerm.c:
https://github.com/xlar54/ultimateii-dos-lib/blob/download_with_punter_protocol/src/ultimateterm.c#L556

    if (datacount == 0) { // datacount == 0 means "disconnected"
        break;
    } else if (datacount > 0) {
        cursor_off();
        if (asciimode) putstring_ascii(uii_data+2); else uii_data_print();
        cursor_on();
    } // datacount == -1 means "wait state"

Can you make some test and verify that it is correct also for your attempts?

**Comment by xlar54** [comment]
From what ive lightly tested tonight, this seems to be true.  Let me run some more vigorous tests tomorrow to be sure as well.
