### ISSUE TITLE
UltimateTerm : X-Modem support

### ISSUE THREAD

**Issue by xlar54** [xlar54/ultimateii-dos-lib#37]
Separating out the xmodem support from the punter support.  Nice work on this!

**Comment by xlar54** [comment]
Works very well for downloading, but currently an issue Im seeing where strange characters after the download completes, either when I type or when the bbs sends some data.  Happens on my U64 and UII+ in both 64 and 128 versions.

**Comment by sblendorio** [comment]
Closed this. Re-open if you notice it again.
