### ISSUE TITLE
UltimateTerm - DOS commands

### ISSUE THREAD

**Issue by xlar54** [xlar54/ultimateii-dos-lib#40]
With the introduction of protocol / download support, I think we need to implement some basic DOS command support as well.  Viewing a directory, rename, delete, copy file (to same disk).  Just the basic options for now.  Also switching active drives for downloads.

**Comment by sblendorio** [comment]
Implemented with last commit:
https://github.com/xlar54/ultimateii-dos-lib/commit/2f7354cc8b1f88b87d1e0de32a3cd09cb179c981
