### ISSUE TITLE
Sample program not working with U2+ Updated to Latest Firmware

### ISSUE THREAD

**Issue by 8bit-Dude** [xlar54/ultimateii-dos-lib#56]
Hi there!

I have a C64G and U2+ which has been updated to the latest firmware (3.10a). My IP settings use DHCP, and I have an IP showing up in the main menu.

But when I give the u_sample.prg program a try, unfortunately everything comes up blank... No IP detected (everything 0.0.0.0), and blank results for all tests.

Is there any particular setting on the U2+ that needs to be setup for the program to work??

**Comment by LeifBloomquist** [comment]
I've found that there is a sensitivity with the Turbo modes with the new 3.10a firmware, anything over 10MHz gives me a problem here with similar symptoms to what you are describing.  Try 1MHz?  Then increase to see is there is an optimal setting.

**Comment by sblendorio** [comment]
Also, please make it sure you're using the latest release of UltimateTerm
https://csdb.dk/release/?id=207440

**Comment by bvl1999** [comment]
In C64 and settings.. make sure you have the ultimate command interface enabled (and make sure it only says enabled, and not something like 'version 1.x'. ), and save the config. power cycle your c64, press the middle button to enter the u2+ menu, press f4, and scroll down to cartridge information, and check what it says there. It will tell you if you have a cartridge enabled which inhibits the ultimate command interface, if so, you need to disable that cartridge (action replay, epyx and fc3 for example) or pick one which does not inhibit use of the ultimate command interface (super snapshot and retro replay for example), and save your config.
