### ISSUE TITLE
U-SHELL doesn't work.. 

### ISSUE THREAD

**Issue by Zibri** [xlar54/ultimateii-dos-lib#58]
I just tried U-SHELL (I have a u2+ on 3.10A fw).
Nothing works, not even the "id" command.

**Comment by Zibri** [comment]
![image](https://user-images.githubusercontent.com/855176/233612782-a6e1052c-c0c2-4277-9c7f-164cbe5f2b81.png)

**Comment by Zibri** [comment]
I tried also the one from the d64..
![image](https://user-images.githubusercontent.com/855176/233613651-d04526e3-986e-4f59-952b-1f2d98e77c0c.png)

**Comment by sblendorio** [comment]
Hi @Zibri

I actually worked on U-Term. Did you try it?
If it works, we can find the difference with other demo programs in order to understand where is the problem

**Comment by sblendorio** [comment]
Hi @Zibri,

at the moment I don't have access neither to a C64 nor to a U2+, but I asked on Ultimate Facebook group to test at least U-Term to people who are using FW 3.10A.

A user tried it with FW 3.10A, 3.10E and in progress 3.10F, he said that u-term64 works well, but he had problems with a customized C128 (he is using something called C128DM), while using u-term128 (80columns) with a vanilla C128, it works well.

So I ask you to try u-term64, see if it works also for you, then I'll investigate on differences between uterm's usage of ultimate-libs and other demo programs.

Link to Facebook thread: https://www.facebook.com/groups/ultimate64/posts/10159924408127753

Regards
Francesco

**Comment by Zibri** [comment]
My bad... it works! It is incompatible with the action replay cartridge.
![image](https://user-images.githubusercontent.com/855176/233692358-a8136201-c28c-4e1a-8fef-404a88a1b4ce.png)

**Comment by Zibri** [comment]
about u-term it does work "sort of" it can't connect anywhere but it's not your fault it's Gideon's:
I set up my U2 with manual IP and there is no entry for DNS server in the manual configuration.. so it can't resolve anything....

**Comment by sblendorio** [comment]
I could implement manual DNS setting in the next release. I also have to write to disable Action Replay in the documentation.

**Comment by sblendorio** [comment]
Serendipty bugfix - thanks to your report (solved), we found an actual timing bug, just in UltimateTerm (the other demos do not use **uci_detect**, so they don't suffer this problem), fixed by Bart van Leeuwen, here is the latest release:

https://csdb.dk/release/index.php?id=231748
