### ISSUE TITLE
Simple HTTP functions

### ISSUE THREAD

**Issue by korbosoft** [xlar54/ultimateii-dos-lib#61]
I'd like to see some HTTP functions (like requesting) in this library. Also, great work on this library!

**Comment by korbosoft** [comment]
not needed

**Comment by LeifBloomquist** [comment]
@korbosoft Yes HTTP stuff would be an application-level function in my opinion.   I implemented a super-simple HTTP requester on top of this library for my ISS tracker, take a look:

https://github.com/LeifBloomquist/iss-tracker-u64/blob/main/u64/src/network.c
